[supervisord]
nodaemon=true
user=root
logfile=/app/data/supervisord.log
pidfile=/var/run/supervisord.pid

[program:postgresql]
command=/app/pkg/start-postgres.sh
user=root
autostart=true
autorestart=true
stdout_logfile=/app/data/postgresql.log
stderr_logfile=/app/data/postgresql_error.log

[program:odoo]
command=/app/pkg/start-odoo.sh
user=root
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
